<Project>
  <PropertyGroup>
    <Authors>Proctorio</Authors>
    <Company>Proctorio</Company>
    <Copyright>Copyright © Proctorio 2025</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/proctorio/json</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/proctorio/json</PackageProjectUrl>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <!-- Code quality settings -->
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>
</Project>
